#!/usr/bin/env python3
"""
Mininet topology generated by ns3-gui
Generated: 2025-12-15T17:21:48.741500
"""

from mininet.net import Mininet
from mininet.node import Controller, OVSSwitch
from mininet.cli import CLI
from mininet.log import setLogLevel

def create_topology():
    net = Mininet(controller=Controller, switch=OVSSwitch)
    
    # Add controller
    net.addController("c0")
    
    # Add nodes
    host_fae6 = net.addHost("host_fae6")
    host_d275 = net.addHost("host_d275")
    switch_dca5 = net.addSwitch("switch_dca5")
    
    # Add links
    net.addLink(host_fae6, switch_dca5)
    net.addLink(host_d275, switch_dca5)
    
    return net

if __name__ == "__main__":
    setLogLevel("info")
    net = create_topology()
    net.start()
    CLI(net)
    net.stop()