#!/usr/bin/env python3
"""
Mininet topology generated by ns3-gui
Generated: 2025-11-26T21:14:01.345743
"""

from mininet.net import Mininet
from mininet.node import Controller, OVSSwitch
from mininet.cli import CLI
from mininet.log import setLogLevel

def create_topology():
    net = Mininet(controller=Controller, switch=OVSSwitch)
    
    # Add controller
    net.addController("c0")
    
    # Add nodes
    host_1524 = net.addHost("host_1524")
    switch_ddef = net.addSwitch("switch_ddef")
    host_5423 = net.addHost("host_5423")
    router_36c9 = net.addHost("router_36c9")
    
    # Add links
    net.addLink(switch_ddef, host_1524)
    net.addLink(host_5423, switch_ddef)
    net.addLink(switch_ddef, router_36c9)
    
    return net

if __name__ == "__main__":
    setLogLevel("info")
    net = create_topology()
    net.start()
    CLI(net)
    net.stop()